import { create } from 'zustand';
import { persist } from 'zustand/middleware';

interface LanguageStore {
  currentLanguage: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Hero Section
    heroTitle: 'Your AI Farming Assistant',
    heroSubtitle: 'Get expert advice on crops, pests, soil, weather, and government schemes in your language',
    listening: 'Listening...',
    tapToSpeak: 'Tap to speak',
    
    // Categories
    crops: 'Crops',
    cropDescription: 'Learn about different crops, planting, and care',
    pests: 'Pests',
    pestDescription: 'Identify and manage crop pests effectively',
    soil: 'Soil',
    soilDescription: 'Understand soil types and improvement methods',
    weather: 'Weather',
    weatherDescription: 'Get location-based weather updates',
    schemes: 'Government Schemes',
    schemesDescription: 'Access government loans and agricultural schemes',
    market: 'Market Analysis',
    marketDescription: 'Analyze market demand for different crops',
    pesticides: 'Pesticides',
    pesticidesDescription: 'Find crop-specific pesticide information',
    water: 'Water Management',
    waterDescription: 'Learn efficient water usage and irrigation',
    diseaseDetection: 'Disease Detection',
    diseaseDescription: 'Upload images to detect crop diseases',
    
    // Chatbot UI
    thinking: 'Thinking...',
    chatbotPlaceholder: 'Ask me about farming...',
    chatbotGreeting: "Hello! Ask me anything about farming.",
    signInToSaveHistory: "Sign in to save your chat history.",
    recording: 'Recording...',
    voice: 'Voice',
    audioOn: 'Audio On',
    audioOff: 'Audio Off',
    youSaid: 'You said:',
    youAreSaying: "You're saying:",
    listeningSpeakNow: 'Listening... Speak now',
    listening: 'Listening...',

    // AI Responses
    aiResponseCrop: 'Based on your question about crops, I recommend checking our crops section for detailed information about planting, care, and harvesting. For specific crop advice, consider factors like your soil type, climate, and local conditions. Would you like me to help you with a particular crop?',
    aiResponsePest: "For pest management, it's important to first identify the specific pest affecting your crops. I can help you with both organic and chemical treatment options. Check our pests section for detailed identification guides and treatment methods. What type of crop are you dealing with?",
    aiResponseSoil: "Soil health is crucial for successful farming. Different soil types require different management approaches. I recommend testing your soil pH and nutrient levels first. Our soil section has comprehensive information about soil types and improvement methods. What's your current soil condition?",
    aiResponseWeather: "Weather plays a vital role in farming decisions. I can provide current weather information and agricultural insights. For irrigation planning, consider both current conditions and forecasts. Check our weather section for detailed agricultural weather guidance.",
    aiResponseMarket: "Market prices fluctuate based on demand, season, and quality. I can help you analyze current market trends and suggest optimal selling times. Our market section provides real-time price information and demand analysis. Which crop are you planning to sell?",
    aiResponseDisease: "Plant diseases can significantly impact your harvest. Early detection is key. You can use our disease detection feature to upload photos of affected plants for AI analysis. I can also provide information about common diseases and their treatments. What symptoms are you observing?",
    aiResponseWater: "Efficient water management is essential for sustainable farming. I can suggest irrigation techniques based on your crop type and local conditions. Our water management section covers various irrigation methods and conservation tips. What's your current irrigation setup?",
    aiResponseScheme: "There are various government schemes available for farmers including subsidies, loans, and insurance programs. I can help you find schemes you're eligible for. Our schemes section has detailed information about application processes and benefits. What type of support are you looking for?",
    aiResponseGreeting: "Hello! I'm your AI farming assistant. I can help you with crops, pests, soil management, weather information, market prices, government schemes, and much more. What farming question can I help you with today?",
    aiResponseDefault: "Thank you for your question! I'm here to help with all your farming needs. I can provide information about crops, pest management, soil health, weather conditions, market prices, government schemes, and more. Could you please be more specific about what you'd like to know? You can also explore our different sections for detailed information.",
    aiResponseError: "Sorry, I encountered an error. Please try again.",

    // Disease Detection Page
    readyToAnalyze: 'Ready to Analyze',
    uploadToStartDetection: 'Upload an image of your crop to get started with disease detection',
    analyzingImage: 'Analyzing image... This may take a few moments.',
    detectionResults: 'Detection Results',
    severity: 'Severity',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    confidence: 'Confidence',
    getExpertConsultation: 'Get Expert Consultation',
    saveResults: 'Save Results',
    commonCropDiseases: 'Common Crop Diseases',
    affects: 'Affects',
    risk: 'Risk',
    selectImage: 'Select Image',
    orClickToSelect: 'or click to select a file',
    tipsForDetection: 'Tips for Better Detection',
    preventionTips: 'Prevention Tips',
    tip1: 'Take clear, well-lit photos of affected plant parts',
    tip2: 'Focus on leaves, stems, or fruits showing symptoms',
    tip3: 'Avoid blurry or distant images',
    tip4: 'Include multiple angles if possible',

    // Weather
    currentWeather: 'Current Weather',
    temperature: 'Temperature',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    condition: 'Condition',
    
    // General
    exploreCategories: 'Explore Categories',
    aiAssistant: 'AI Assistant',
    aiDescription: 'Ask questions about farming, get personalized advice, and access expert knowledge in your preferred language',
    askQuestion: 'Ask a Question',
    learnMore: 'Learn More',
    
    // Footer
    footerDescription: 'Empowering Indian farmers with AI-powered agricultural assistance',
    features: 'Features',
    voiceAssistant: 'Voice Assistant',
    cropGuidance: 'Crop Guidance',
    pestManagement: 'Pest Management',
    weatherUpdates: 'Weather Updates',
    support: 'Support',
    helpCenter: 'Help Center',
    tutorials: 'Tutorials',
    contact: 'Contact',
    feedback: 'Feedback',
    languages: 'Languages',
    allRightsReserved: 'All rights reserved.',
    
    // Navigation
    home: 'Home',
    profile: 'Profile',
    settings: 'Settings',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    
    // Chat
    chatHistory: 'Chat History',
    startChatting: 'Start Chatting',
    totalConversations: 'Total Conversations',
    todaysChats: "Today's Chats",
    daysActive: 'Days Active',
    
    // Common
    back: 'Back',
    noCropsFound: 'No crops found',
    noPestsFound: 'No pests found',
    noSoilTypesFound: 'No soil types found',
    noSchemesFound: 'No schemes found',
    noPesticidesFound: 'No pesticides found',
    noTechniquesFound: 'No techniques found',
    tryDifferentSearch: 'Try a different search',
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    
    // Crops
    cropName: 'Crop Name',
    plantingInstructions: 'Planting Instructions',
    careGuidelines: 'Care Guidelines',
    harvestingInfo: 'Harvesting Information',
    expectedYield: 'Expected Yield',
    suitableRegions: 'Suitable Regions',
    
    // Pests
    pestName: 'Pest Name',
    scientificName: 'Scientific Name',
    identification: 'Identification',
    damage: 'Damage Caused',
    organicManagement: 'Organic Management',
    chemicalManagement: 'Chemical Management',
    affectedCrops: 'Affected Crops',
    
    // Soil
    soilType: 'Soil Type',
    properties: 'Key Properties',
    distribution: 'Geographical Distribution',
    suitableCrops: 'Suitable Crops',
    improvements: 'Health Improvement Recommendations',
    
    // Government Schemes
    schemeName: 'Scheme Name',
    description: 'Description',
    benefits: 'Benefits',
    eligibility: 'Eligibility Criteria',
    applicationProcess: 'Application Process',
    officialUrl: 'Official Website',
    launchDate: 'Launch Date',
    
    // Pesticides
    pesticideName: 'Pesticide Name',
    pesticideType: 'Type',
    activeIngredients: 'Active Ingredients',
    targetCrops: 'Target Crops',
    applicationInstructions: 'Application Instructions',
    safetyPrecautions: 'Safety Precautions',
    
    // Water Management
    techniqueName: 'Technique Name',
    irrigationMethod: 'Irrigation Method',
    conservationTips: 'Conservation Tips',
    applicableCrops: 'Applicable Crops',
    
    // Disease Detection
    uploadImage: 'Upload Image',
    detectDisease: 'Detect Disease',
    symptoms: 'Symptoms',
    causes: 'Causes',
    treatment: 'Treatment Options',
  },
  ta: {
    // Hero Section
    heroTitle: 'உங்கள் AI விவசாய உதவியாளர்',
    heroSubtitle: 'பயிர்கள், பூச்சிகள், மண், வானிலை மற்றும் அரசு திட்டங்கள் பற்றிய நிபுணர் ஆலோசனையை உங்கள் மொழியில் பெறுங்கள்',
    listening: 'கேட்டுக்கொண்டிருக்கிறது...',
    tapToSpeak: 'பேச தட்டவும்',
    
    // Categories
    crops: 'பயிர்கள்',
    cropDescription: 'பல்வேறு பயிர்கள், நடவு மற்றும் பராமரிப்பு பற்றி அறியுங்கள்',
    pests: 'பூச்சிகள்',
    pestDescription: 'பயிர் பூச்சிகளை திறம்பட அடையாளம் கண்டு நிர்வகிக்கவும்',
    soil: 'மண்',
    soilDescription: 'மண் வகைகள் மற்றும் மேம்பாட்டு முறைகளை புரிந்துகொள்ளுங்கள்',
    weather: 'வானிலை',
    weatherDescription: 'இடம் சார்ந்த வானிலை புதுப்பிப்புகளை பெறுங்கள்',
    schemes: 'அரசு திட்டங்கள்',
    schemesDescription: 'அரசு கடன்கள் மற்றும் விவசாய திட்டங்களை அணுகவும்',
    market: 'சந்தை பகுப்பாய்வு',
    marketDescription: 'பல்வேறு பயிர்களுக்கான சந்தை தேவையை பகுப்பாய்வு செய்யுங்கள்',
    pesticides: 'பூச்சிக்கொல்லிகள்',
    pesticidesDescription: 'பயிர் சார்ந்த பூச்சிக்கொல்லி தகவல்களை கண்டறியுங்கள்',
    water: 'நீர் மேலாண்மை',
    waterDescription: 'திறமையான நீர் பயன்பாடு மற்றும் நீர்ப்பாசனம் கற்றுக்கொள்ளுங்கள்',
    diseaseDetection: 'நோய் கண்டறிதல்',
    diseaseDescription: 'பயிர் நோய்களை கண்டறிய படங்களை பதிவேற்றவும்',
    
    // Chatbot UI
    thinking: 'சிந்திக்கிறது...',
    chatbotPlaceholder: 'விவசாயத்தைப் பற்றி என்னிடம் கேளுங்கள்...',
    chatbotGreeting: "வணக்கம்! விவசாயம் பற்றி எதையும் கேளுங்கள்.",
    signInToSaveHistory: "உங்கள் அரட்டை வரலாற்றைச் சேமிக்க உள்நுழையவும்.",
    recording: 'பதிவு செய்கிறது...',
    voice: 'குரல்',
    audioOn: 'ஆடியோ ஆன்',
    audioOff: 'ஆடியோ ஆஃப்',
    youSaid: 'நீங்கள் சொன்னது:',
    youAreSaying: "நீங்கள் சொல்கிறீர்கள்:",
    listeningSpeakNow: 'கேட்டுக்கொண்டிருக்கிறது... இப்போது பேசுங்கள்',
    listening: 'கேட்டுக்கொண்டிருக்கிறது...',

    // AI Responses
    aiResponseCrop: 'பயிர்கள் குறித்த உங்கள் கேள்வியின் அடிப்படையில், நடவு, பராமரிப்பு மற்றும் அறுவடை பற்றிய விரிவான தகவலுக்கு எங்கள் பயிர்கள் பகுதியைச் சரிபார்க்க பரிந்துரைக்கிறேன். குறிப்பிட்ட பயிர் ஆலோசனைக்கு, உங்கள் மண் வகை, காலநிலை மற்றும் உள்ளூர் நிலைமைகள் போன்ற காரணிகளைக் கவனியுங்கள். ஒரு குறிப்பிட்ட பயிருக்கு நான் உங்களுக்கு உதவ வேண்டுமா?',
    aiResponsePest: "பூச்சி மேலாண்மைக்கு, முதலில் உங்கள் பயிர்களை பாதிக்கும் குறிப்பிட்ட பூச்சியை அடையாளம் காண்பது முக்கியம். இயற்கை மற்றும் ரசாயன சிகிச்சை முறைகள் இரண்டிற்கும் நான் உங்களுக்கு உதவ முடியும். விரிவான அடையாள வழிகாட்டிகள் மற்றும் சிகிச்சை முறைகளுக்கு எங்கள் பூச்சிகள் பகுதியைச் சரிபார்க்கவும். நீங்கள் எந்த வகையான பயிருடன் வேலை செய்கிறீர்கள்?",
    aiResponseSoil: "வெற்றிகரமான விவசாயத்திற்கு மண்ணின் ஆரோக்கியம் முக்கியமானது. வெவ்வேறு மண் வகைகளுக்கு வெவ்வேறு மேலாண்மை அணுகுமுறைகள் தேவைப்படுகின்றன. முதலில் உங்கள் மண்ணின் pH மற்றும் ஊட்டச்சத்து அளவை சோதிக்க பரிந்துரைக்கிறேன். மண் வகைகள் மற்றும் மேம்பாட்டு முறைகள் பற்றிய விரிவான தகவல்களை எங்கள் மண் பகுதி கொண்டுள்ளது. உங்கள் தற்போதைய மண் நிலை என்ன?",
    aiResponseWeather: "விவசாய முடிவுகளில் வானிலை முக்கிய பங்கு வகிக்கிறது. நான் தற்போதைய வானிலை தகவல் மற்றும் விவசாய நுண்ணறிவுகளை வழங்க முடியும். நீர்ப்பாசனத் திட்டமிடலுக்கு, தற்போதைய நிலைமைகள் மற்றும் முன்னறிவிப்புகள் இரண்டையும் கவனியுங்கள். விரிவான விவசாய வானிலை வழிகாட்டுதலுக்கு எங்கள் வானிலை பகுதியைச் சரிபார்க்கவும்.",
    aiResponseMarket: "தேவை, பருவம் மற்றும் தரம் ஆகியவற்றின் அடிப்படையில் சந்தை விலைகள் ஏற்ற இறக்கத்துடன் இருக்கும். தற்போதைய சந்தைப் போக்குகளைப் பகுப்பாய்வு செய்யவும், உகந்த விற்பனை நேரங்களைப் பரிந்துரைக்கவும் நான் உங்களுக்கு உதவ முடியும். எங்கள் சந்தைப் பகுதி நிகழ்நேர விலை தகவல் மற்றும் தேவை பகுப்பாய்வை வழங்குகிறது. நீங்கள் எந்தப் பயிரை விற்கத் திட்டமிட்டுள்ளீர்கள்?",
    aiResponseDisease: "தாவர நோய்கள் உங்கள் அறுவடையை கணிசமாக பாதிக்கும். முன்கூட்டியே கண்டறிவதே முக்கியம். AI பகுப்பாய்விற்காக பாதிக்கப்பட்ட தாவரங்களின் புகைப்படங்களைப் பதிவேற்ற எங்களது நோய் கண்டறிதல் அம்சத்தைப் பயன்படுத்தலாம். பொதுவான நோய்கள் மற்றும் அவற்றின் சிகிச்சைகள் பற்றிய தகவலையும் நான் வழங்க முடியும். நீங்கள் என்ன அறிகுறிகளைக் கவனிக்கிறீர்கள்?",
    aiResponseWater: "நிலையான விவசாயத்திற்கு திறமையான நீர் மேலாண்மை அவசியம். உங்கள் பயிர் வகை மற்றும் உள்ளூர் நிலைமைகளின் அடிப்படையில் நீர்ப்பாசன நுட்பங்களை நான் பரிந்துரைக்க முடியும். எங்களது நீர் மேலாண்மை பகுதி பல்வேறு நீர்ப்பாசன முறைகள் மற்றும் பாதுகாப்பு குறிப்புகளை உள்ளடக்கியது. உங்கள் தற்போதைய நீர்ப்பாசன அமைப்பு என்ன?",
    aiResponseScheme: "மானியங்கள், கடன்கள் மற்றும் காப்பீட்டுத் திட்டங்கள் உட்பட விவசாயிகளுக்கு பல்வேறு அரசு திட்டங்கள் உள்ளன. நீங்கள் தகுதியுள்ள திட்டங்களைக் கண்டறிய நான் உங்களுக்கு உதவ முடியும். எங்களது திட்டங்கள் பகுதியில் விண்ணப்ப செயல்முறைகள் மற்றும் நன்மைகள் பற்றிய விரிவான தகவல்கள் உள்ளன. நீங்கள் எந்த வகையான ஆதரவைத் தேடுகிறீர்கள்?",
    aiResponseGreeting: "வணக்கம்! நான் உங்கள் AI விவசாய உதவியாளர். பயிர்கள், பூச்சிகள், மண் மேலாண்மை, வானிலை தகவல், சந்தை விலைகள், அரசு திட்டங்கள் மற்றும் பலவற்றில் நான் உங்களுக்கு உதவ முடியும். இன்று நான் உங்களுக்கு எந்த விவசாயக் கேள்வியில் உதவ முடியும்?",
    aiResponseDefault: "உங்கள் கேள்விக்கு நன்றி! உங்கள் விவசாயத் தேவைகள் அனைத்திற்கும் உதவ நான் இங்கே இருக்கிறேன். பயிர்கள், பூச்சி மேலாண்மை, மண் ஆரோக்கியம், வானிலை நிலைமைகள், சந்தை விலைகள், அரசு திட்டங்கள் மற்றும் பலவற்றைப் பற்றிய தகவல்களை நான் வழங்க முடியும். நீங்கள் எதைப் பற்றி தெரிந்து கொள்ள விரும்புகிறீர்கள் என்பதில் இன்னும் கொஞ்சம் தெளிவாக இருக்க முடியுமா? விரிவான தகவலுக்கு எங்கள் வெவ்வேறு பகுதிகளையும் நீங்கள் ஆராயலாம்.",
    aiResponseError: "மன்னிக்கவும், எனக்கு ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",

    // Disease Detection Page
    readyToAnalyze: 'ஆராயத் தயார்',
    uploadToStartDetection: 'நோய் கண்டறிதலைத் தொடங்க உங்கள் பயிரின் படத்தைப் பதிவேற்றவும்',
    analyzingImage: 'படத்தை ஆராய்கிறது... இதற்கு சிறிது நேரம் ஆகலாம்.',
    detectionResults: 'கண்டறிதல் முடிவுகள்',
    severity: 'தீவிரம்',
    high: 'அதிகம்',
    medium: 'நடுத்தரம்',
    low: 'குறைவு',
    confidence: 'நம்பிக்கை',
    getExpertConsultation: 'நிபுணர் ஆலோசனையைப் பெறுங்கள்',
    saveResults: 'முடிவுகளைச் சேமிக்கவும்',
    commonCropDiseases: 'பொதுவான பயிர் நோய்கள்',
    affects: 'பாதிக்கிறது',
    risk: 'ஆபத்து',
    selectImage: 'படத்தைத் தேர்ந்தெடுக்கவும்',
    orClickToSelect: 'அல்லது ஒரு கோப்பைத் தேர்ந்தெடுக்க கிளிக் செய்யவும்',
    tipsForDetection: 'சிறந்த கண்டறிதலுக்கான உதவிக்குறிப்புகள்',
    preventionTips: 'தடுப்பு குறிப்புகள்',
    tip1: 'பாதிக்கப்பட்ட தாவர பாகங்களின் தெளிவான, நன்கு ஒளிரும் புகைப்படங்களை எடுக்கவும்',
    tip2: 'அறிகுறிகளைக் காட்டும் இலைகள், தண்டுகள் அல்லது பழங்களில் கவனம் செலுத்துங்கள்',
    tip3: 'மங்கலான அல்லது தொலைதூர படங்களைத் தவிர்க்கவும்',
    tip4: 'முடிந்தால் பல கோணங்களைச் சேர்க்கவும்',

    // Weather
    currentWeather: 'தற்போதைய வானிலை',
    temperature: 'வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    windSpeed: 'காற்றின் வேகம்',
    condition: 'நிலை',
    
    // General
    exploreCategories: 'வகைகளை ஆராயுங்கள்',
    aiAssistant: 'AI உதவியாளர்',
    aiDescription: 'விவசாயம் பற்றி கேள்விகள் கேளுங்கள், தனிப்பயனாக்கப்பட்ட ஆலோசனையை பெறுங்கள், மற்றும் உங்கள் விருப்பமான மொழியில் நிபுணர் அறிவை அணுகவும்',
    askQuestion: 'கேள்வி கேளுங்கள்',
    learnMore: 'மேலும் அறியுங்கள்',
    
    // Footer
    footerDescription: 'AI-இயங்கும் விவசாய உதவியுடன் இந்திய விவசாயிகளை மேம்படுத்துதல்',
    features: 'அம்சங்கள்',
    voiceAssistant: 'குரல் உதவியாளர்',
    cropGuidance: 'பயிர் வழிகாட்டுதல்',
    pestManagement: 'பூச்சி மேலாண்மை',
    weatherUpdates: 'வானிலை புதுப்பிப்புகள்',
    support: 'ஆதரவு',
    helpCenter: 'உதவி மையம்',
    tutorials: 'பயிற்சிகள்',
    contact: 'தொடர்பு',
    feedback: 'கருத்து',
    languages: 'மொழிகள்',
    allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    
    // Navigation
    home: 'முகப்பு',
    profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்',
    signIn: 'உள்நுழைய',
    signOut: 'வெளியேறு',
    
    // Chat
    chatHistory: 'அரட்டை வரலாறு',
    startChatting: 'அரட்டை தொடங்கு',
    totalConversations: 'மொத்த உரையாடல்கள்',
    todaysChats: 'இன்றைய அரட்டைகள்',
    daysActive: 'செயல்பாட்டு நாட்கள்',
    
    // Common
    loading: 'ஏற்றுகிறது...',
    error: 'பிழை',
    retry: 'மீண்டும் முயற்சி',
    save: 'சேமி',
    cancel: 'ரத்து',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    add: 'சேர்',
    search: 'தேடு',
    filter: 'வடிகட்டு',
    sort: 'வரிசைப்படுத்து',
    
    // Additional translations for Tamil...
    back: 'பின்னால்',
    noCropsFound: 'பயிர்கள் கிடைக்கவில்லை',
    noPestsFound: 'பூச்சிகள் கிடைக்கவில்லை',
    noSoilTypesFound: 'மண் வகைகள் கிடைக்கவில்லை',
    noSchemesFound: 'திட்டங்கள் கிடைக்கவில்லை',
    noPesticidesFound: 'பூச்சிக்கொல்லிகள் கிடைக்கவில்லை',
    noTechniquesFound: 'நுட்பங்கள் கிடைக்கவில்லை',
    tryDifferentSearch: 'வேறு தேடல் முயற்சி செய்யுங்கள்',
    cropName: 'பயிர் பெயர்',
    plantingInstructions: 'நடவு வழிமுறைகள்',
    careGuidelines: 'பராமரிப்பு வழிகாட்டுதல்கள்',
    harvestingInfo: 'அறுவடை தகவல்',
    expectedYield: 'எதிர்பார்க்கப்படும் விளைச்சல்',
    suitableRegions: 'பொருத்தமான பகுதிகள்',
    
    pestName: 'பூச்சி பெயர்',
    scientificName: 'அறிவியல் பெயர்',
    identification: 'அடையாளம்',
    damage: 'ஏற்படும் சேதம்',
    organicManagement: 'இயற்கை மேலாண்மை',
    chemicalManagement: 'இரசாயன மேலாண்மை',
    affectedCrops: 'பாதிக்கப்பட்ட பயிர்கள்',
    
    soilType: 'மண் வகை',
    properties: 'முக்கிய பண்புகள்',
    distribution: 'புவியியல் விநியோகம்',
    suitableCrops: 'பொருத்தமான பயிர்கள்',
    improvements: 'ஆரோக்கிய மேம்பாட்டு பரிந்துரைகள்',
    
    schemeName: 'திட்ட பெயர்',
    description: 'விவரம்',
    benefits: 'நன்மைகள்',
    eligibility: 'தகுதி நிபந்தனைகள்',
    applicationProcess: 'விண்ணப்ப செயல்முறை',
    officialUrl: 'அதிகாரப்பூர்வ இணையதளம்',
    launchDate: 'தொடக்க தேதி',
    
    pesticideName: 'பூச்சிக்கொல்லி பெயர்',
    pesticideType: 'வகை',
    activeIngredients: 'செயல்படும் பொருட்கள்',
    targetCrops: 'இலக்கு பயிர்கள்',
    applicationInstructions: 'பயன்பாட்டு வழிமுறைகள்',
    safetyPrecautions: 'பாதுகாப்பு முன்னெச்சரிக்கைகள்',
    
    techniqueName: 'நுட்ப பெயர்',
    irrigationMethod: 'நீர்ப்பாசன முறை',
    conservationTips: 'பாதுகாப்பு குறிப்புகள்',
    applicableCrops: 'பொருந்தும் பயிர்கள்',
    
    uploadImage: 'படம் பதிவேற்று',
    detectDisease: 'நோயை கண்டறி',
    symptoms: 'அறிகுறிகள்',
    causes: 'காரணங்கள்',
    treatment: 'சிகிச்சை விருப்பங்கள்',
  },
  te: {
    // Hero Section
    heroTitle: 'మీ AI వ్యవసాయ సహాయకుడు',
    heroSubtitle: 'మీ భాషలో పంటలు, చీడపురుగులు, మట్టి, వాతావరణం మరియు ప్రభుత్వ పథకాలపై నిపుణుల సలహా పొందండి',
    listening: 'వింటున్నాం...',
    tapToSpeak: 'మాట్లాడటానికి నొక్కండి',
    
    // Categories
    crops: 'పంటలు',
    cropDescription: 'వివిధ పంటలు, నాటడం మరియు సంరక్షణ గురించి తెలుసుకోండి',
    pests: 'చీడపురుగులు',
    pestDescription: 'పంట చీడపురుగులను సమర్థవంతంగా గుర్తించి నిర్వహించండి',
    soil: 'మట్టి',
    soilDescription: 'మట్టి రకాలు మరియు మెరుగుదల పద్ధతులను అర్థం చేసుకోండి',
    weather: 'వాతావరణం',
    weatherDescription: 'స్థాన ఆధారిత వాతావరణ నవీకరణలను పొందండి',
    schemes: 'ప్రభుత్వ పథకాలు',
    schemesDescription: 'ప్రభుత్వ రుణాలు మరియు వ్యవసాయ పథకాలను యాక్సెస్ చేయండి',
    market: 'మార్కెట్ విశ్లేషణ',
    marketDescription: 'వివిధ పంటలకు మార్కెట్ డిమాండ్‌ను విశ్లేషించండి',
    pesticides: 'పురుగుమందులు',
    pesticidesDescription: 'పంట-నిర్దిష్ట పురుగుమందు సమాచారాన్ని కనుగొనండి',
    water: 'నీటి నిర్వహణ',
    waterDescription: 'సమర్థవంతమైన నీటి వినియోగం మరియు నీటిపారుదల నేర్చుకోండి',
    diseaseDetection: 'వ్యాధి గుర్తింపు',
    diseaseDescription: 'పంట వ్యాధులను గుర్తించడానికి చిత్రాలను అప్‌లోడ్ చేయండి',
    
    // Chatbot UI
    thinking: 'ఆలోచిస్తోంది...',
    chatbotPlaceholder: 'వ్యవసాయం గురించి నన్ను అడగండి...',
    chatbotGreeting: "హలో! వ్యవసాయం గురించి ఏదైనా అడగండి.",
    signInToSaveHistory: "మీ చాట్ చరిత్రను సేవ్ చేయడానికి సైన్ ఇన్ చేయండి.",
    recording: 'రికార్డింగ్...',
    voice: 'వాయిస్',
    audioOn: 'ఆడియో ఆన్',
    audioOff: 'ఆడియో ఆఫ్',
    youSaid: 'మీరు చెప్పారు:',
    youAreSaying: "మీరు చెబుతున్నారు:",
    listeningSpeakNow: 'వింటున్నాం... ఇప్పుడు మాట్లాడండి',
    listening: 'వింటున్నాం...',

    // AI Responses
    aiResponseCrop: 'పంటల గురించి మీ ప్రశ్న ఆధారంగా, నాటడం, సంరక్షణ మరియు కోత గురించి వివరణాత్మక సమాచారం కోసం మా పంటల విభాగాన్ని తనిఖీ చేయాలని నేను సిఫార్సు చేస్తున్నాను. నిర్దిష్ట పంట సలహా కోసం, మీ నేల రకం, వాతావరణం మరియు స్థానిక పరిస్థితుల వంటి అంశాలను పరిగణించండి. నేను మీకు ఏదైనా నిర్దిష్ట పంట విషయంలో సహాయం చేయాలా?',
    aiResponsePest: "చీడపురుగుల నిర్వహణ కోసం, మొదట మీ పంటలను ప్రభావితం చేసే నిర్దిష్ట చీడపురుగును గుర్తించడం ముఖ్యం. సేంద్రీయ మరియు రసాయన చికిత్స ఎంపికలు రెండింటిలోనూ నేను మీకు సహాయం చేయగలను. వివరణాత్మక గుర్తింపు మార్గదర్శకాలు మరియు చికిత్స పద్ధతుల కోసం మా చీడపురుగుల విభాగాన్ని తనిఖీ చేయండి. మీరు ఏ రకమైన పంటతో వ్యవహరిస్తున్నారు?",
    aiResponseSoil: "విజయవంతమైన వ్యవసాయానికి నేల ఆరోగ్యం కీలకం. వేర్వేరు నేల రకాలకు వేర్వేరు నిర్వహణ పద్ధతులు అవసరం. మొదట మీ నేల pH మరియు పోషక స్థాయిలను పరీక్షించమని నేను సిఫార్సు చేస్తున్నాను. మా నేల విభాగంలో నేల రకాలు మరియు మెరుగుదల పద్ధతుల గురించి సమగ్ర సమాచారం ఉంది. మీ ప్రస్తుత నేల పరిస్థితి ఎలా ఉంది?",
    aiResponseWeather: "వ్యవసాయ నిర్ణయాలలో వాతావరణం కీలక పాత్ర పోషిస్తుంది. నేను ప్రస్తుత వాతావరణ సమాచారాన్ని మరియు వ్యవసాయ అంతర్దృష్టులను అందించగలను. నీటిపారుదల ప్రణాళిక కోసం, ప్రస్తుత పరిస్థితులు మరియు అంచనాలు రెండింటినీ పరిగణించండి. వివరణాత్మక వ్యవసాయ వాతావరణ మార్గదర్శకత్వం కోసం మా వాతావరణ విభాగాన్ని తనిఖీ చేయండి.",
    aiResponseMarket: "డిమాండ్, సీజన్ మరియు నాణ్యత ఆధారంగా మార్కెట్ ధరలు మారుతూ ఉంటాయి. ప్రస్తుత మార్కెట్ పోకడలను విశ్లేషించడానికి మరియు సరైన విక్రయ సమయాలను సూచించడానికి నేను మీకు సహాయం చేయగలను. మా మార్కెట్ విభాగం నిజ-సమయ ధరల సమాచారాన్ని మరియు డిమాండ్ విశ్లేషణను అందిస్తుంది. మీరు ఏ పంటను విక్రయించాలని ప్లాన్ చేస్తున్నారు?",
    aiResponseDisease: "మొక్కల వ్యాధులు మీ దిగుబడిని గణనీయంగా ప్రభావితం చేస్తాయి. ముందస్తు గుర్తింపు కీలకం. AI విశ్లేషణ కోసం ప్రభావిత మొక్కల ఫోటోలను అప్‌లోడ్ చేయడానికి మీరు మా వ్యాధి గుర్తింపు ఫీచర్‌ను ఉపయోగించవచ్చు. నేను సాధారణ వ్యాధులు మరియు వాటి చికిత్సల గురించి కూడా సమాచారాన్ని అందించగలను. మీరు ఏ లక్షణాలను గమనిస్తున్నారు?",
    aiResponseWater: "స్థిరమైన వ్యవసాయానికి సమర్థవంతమైన నీటి నిర్వహణ అవసరం. మీ పంట రకం మరియు స్థానిక పరిస్థితుల ఆధారంగా నేను నీటిపారుదల పద్ధతులను సూచించగలను. మా నీటి నిర్వహణ విభాగం వివిధ నీటిపారుదల పద్ధతులు మరియు పరిరక్షణ చిట్కాలను కవర్ చేస్తుంది. మీ ప్రస్తుత నీటిపారుదల వ్యవస్థ ఎలా ఉంది?",
    aiResponseScheme: "సబ్సిడీలు, రుణాలు మరియు బీమా కార్యక్రమాలతో సహా రైతుల కోసం వివిధ ప్రభుత్వ పథకాలు అందుబాటులో ఉన్నాయి. మీరు అర్హత పొందే పథకాలను కనుగొనడంలో నేను మీకు సహాయం చేయగలను. మా పథకాల విభాగంలో దరఖాస్తు ప్రక్రియలు మరియు ప్రయోజనాల గురించి వివరణాత్మక సమాచారం ఉంది. మీరు ఏ రకమైన మద్దతు కోసం చూస్తున్నారు?",
    aiResponseGreeting: "హలో! నేను మీ AI వ్యవసాయ సహాయకుడిని. పంటలు, చీడపురుగులు, నేల నిర్వహణ, వాతావరణ సమాచారం, మార్కెట్ ధరలు, ప్రభుత్వ పథకాలు మరియు మరెన్నో విషయాలలో నేను మీకు సహాయం చేయగలను. ఈ రోజు నేను మీకు ఏ వ్యవసాయ ప్రశ్నలో సహాయం చేయగలను?",
    aiResponseDefault: "మీ ప్రశ్నకు ధన్యవాదాలు! మీ వ్యవసాయ అవసరాలన్నింటిలో సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను. నేను పంటలు, చీడపురుగుల నిర్వహణ, నేల ఆరోగ్యం, వాతావరణ పరిస్థితులు, మార్కెట్ ధరలు, ప్రభుత్వ పథకాలు మరియు మరిన్నింటి గురించి సమాచారాన్ని అందించగలను. మీరు దేని గురించి తెలుసుకోవాలనుకుంటున్నారో దయచేసి మరింత స్పష్టంగా చెప్పగలరా? మీరు వివరణాత్మక సమాచారం కోసం మా వివిధ విభాగాలను కూడా అన్వేషించవచ్చు.",
    aiResponseError: "క్షమించండి, నాకు ఒక లోపం ఎదురైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",

    // Disease Detection Page
    readyToAnalyze: 'విశ్లేషణకు సిద్ధంగా ఉంది',
    uploadToStartDetection: 'వ్యాధి గుర్తింపును ప్రారంభించడానికి మీ పంట చిత్రాన్ని అప్‌లోడ్ చేయండి',
    analyzingImage: 'చిత్రాన్ని విశ్లేషిస్తోంది... దీనికి కొంత సమయం పట్టవచ్చు.',
    detectionResults: 'గుర్తింపు ఫలితాలు',
    severity: 'తీవ్రత',
    high: 'అధికం',
    medium: 'మధ్యస్థం',
    low: 'తక్కువ',
    confidence: 'విశ్వాసం',
    getExpertConsultation: 'నిపుణుల సంప్రదింపులను పొందండి',
    saveResults: 'ఫలితాలను సేవ్ చేయండి',
    commonCropDiseases: 'సాధారణ పంట వ్యాధులు',
    affects: 'ప్రభావితం చేస్తుంది',
    risk: 'ప్రమాదం',
    selectImage: 'చిత్రాన్ని ఎంచుకోండి',
    orClickToSelect: 'లేదా ఫైల్‌ను ఎంచుకోవడానికి క్లిక్ చేయండి',
    tipsForDetection: 'మెరుగైన గుర్తింపు కోసం చిట్కాలు',
    preventionTips: 'నివారణ చిట్కాలు',
    tip1: 'ప్రభావిత మొక్కల భాగాల స్పష్టమైన, బాగా వెలుతురు ఉన్న ఫోటోలను తీయండి',
    tip2: 'లక్షణాలు చూపే ఆకులు, కాండం లేదా పండ్లపై దృష్టి పెట్టండి',
    tip3: 'అస్పష్టమైన లేదా దూరంగా ఉన్న చిత్రాలను నివారించండి',
    tip4: 'సాధ్యమైతే బహుళ కోణాలను చేర్చండి',

    // Weather
    currentWeather: 'ప్రస్తుత వాతావరణం',
    temperature: 'ఉష్ణోగ్రత',
    humidity: 'తేమ',
    windSpeed: 'గాలి వేగం',
    condition: 'స్థితి',
    
    // General
    exploreCategories: 'వర్గాలను అన్వేషించండి',
    aiAssistant: 'AI సహాయకుడు',
    aiDescription: 'వ్యవసాయం గురించి ప్రశ్నలు అడగండి, వ్యక్తిగతీకరించిన సలహా పొందండి మరియు మీ ఇష్టమైన భాషలో నిపుణుల జ్ఞానాన్ని యాక్సెస్ చేయండి',
    askQuestion: 'ప్రశ్న అడగండి',
    learnMore: 'మరింత తెలుసుకోండి',
    
    // Footer
    footerDescription: 'AI-శక్తితో కూడిన వ్యవసాయ సహాయంతో భారతీయ రైతులను శక్తివంతం చేయడం',
    features: 'లక్షణాలు',
    voiceAssistant: 'వాయిస్ అసిస్టెంట్',
    cropGuidance: 'పంట మార్గదర్శకత్వం',
    pestManagement: 'చీడపురుగుల నిర్వహణ',
    weatherUpdates: 'వాతావరణ నవీకరణలు',
    support: 'మద్దతు',
    helpCenter: 'సహాయ కేంద్రం',
    tutorials: 'ట్యుటోరియల్స్',
    contact: 'సంప్రదింపు',
    feedback: 'అభిప్రాయం',
    languages: 'భాషలు',
    allRightsReserved: 'అన్ని హక్కులు రక్షించబడ్డాయి.',
    
    // Navigation and other common terms
    home: 'హోమ్',
    profile: 'ప్రొఫైల్',
    settings: 'సెట్టింగ్స్',
    signIn: 'సైన్ ఇన్',
    signOut: 'సైన్ అవుట్',
    
    // Chat
    chatHistory: 'చాట్ చరిత్ర',
    startChatting: 'చాట్ ప్రారంభించండి',
    totalConversations: 'మొత్తం సంభాషణలు',
    todaysChats: 'నేటి చాట్‌లు',
    daysActive: 'క్రియాశీల దినాలు',
    
    loading: 'లోడ్ అవుతోంది...',
    error: 'లోపం',
    retry: 'మళ్లీ ప్రయత్నించండి',
    save: 'సేవ్',
    cancel: 'రద్దు',
    delete: 'తొలగించు',
    edit: 'సవరించు',
    add: 'జోడించు',
    search: 'వెతకండి',
    filter: 'ఫిల్టర్',
    sort: 'క్రమబద్ధీకరించు',
    
    // Additional Telugu translations...
    back: 'వెనుకకు',
    noCropsFound: 'పంటలు కనుగొనబడలేదు',
    noPestsFound: 'చీడపురుగులు కనుగొనబడలేదు',
    noSoilTypesFound: 'మట్టి రకాలు కనుగొనబడలేదు',
    noSchemesFound: 'పథకాలు కనుగొనబడలేదు',
    noPesticidesFound: 'పురుగుమందులు కనుగొనబడలేదు',
    noTechniquesFound: 'టెక్నిక్‌లు కనుగొనబడలేదు',
    tryDifferentSearch: 'వేరే వెతుకులాట ప్రయత్నించండి',
    cropName: 'పంట పేరు',
    plantingInstructions: 'నాటడం సూచనలు',
    careGuidelines: 'సంరక్షణ మార్గదర్శకాలు',
    harvestingInfo: 'కోత సమాచారం',
    expectedYield: 'ఆశించిన దిగుబడి',
    suitableRegions: 'అనుకూలమైన ప్రాంతాలు',
    
    pestName: 'చీడపురుగు పేరు',
    scientificName: 'శాస్త్రీయ నామం',
    identification: 'గుర్తింపు',
    damage: 'కలిగే నష్టం',
    organicManagement: 'సేంద్రీయ నిర్వహణ',
    chemicalManagement: 'రసాయన నిర్వహణ',
    affectedCrops: 'ప్రభావిత పంటలు',
    
    soilType: 'మట్టి రకం',
    properties: 'ముఖ్య లక్షణాలు',
    distribution: 'భౌగోళిక పంపిణీ',
    suitableCrops: 'అనుకూలమైన పంటలు',
    improvements: 'ఆరోగ్య మెరుగుదల సిఫార్సులు',
    
    schemeName: 'పథకం పేరు',
    description: 'వివరణ',
    benefits: 'ప్రయోజనాలు',
    eligibility: 'అర్హత ప్రమాణాలు',
    applicationProcess: 'దరఖాస్తు ప్రక్రియ',
    officialUrl: 'అధికారిక వెబ్‌సైట్',
    launchDate: 'ప్రారంభ తేదీ',
    
    pesticideName: 'పురుగుమందు పేరు',
    pesticideType: 'రకం',
    activeIngredients: 'క్రియాశీల పదార్థాలు',
    targetCrops: 'లక్ష్య పంటలు',
    applicationInstructions: 'అప్లికేషన్ సూచనలు',
    safetyPrecautions: 'భద్రతా జాగ్రత్తలు',
    
    techniqueName: 'టెక్నిక్ పేరు',
    irrigationMethod: 'నీటిపారుదల పద్ధతి',
    conservationTips: 'సంరక్షణ చిట్కాలు',
    applicableCrops: 'వర్తించే పంటలు',
    
    uploadImage: 'చిత్రం అప్‌లోడ్ చేయండి',
    detectDisease: 'వ్యాధిని గుర్తించండి',
    symptoms: 'లక్షణాలు',
    causes: 'కారణాలు',
    treatment: 'చికిత్స ఎంపికలు',
  },
  hi: {
    // Hero Section
    heroTitle: 'आपका AI कृषि सहायक',
    heroSubtitle: 'अपनी भाषा में फसलों, कीटों, मिट्टी, मौसम और सरकारी योजनाओं पर विशेषज्ञ सलाह प्राप्त करें',
    listening: 'सुन रहा है...',
    tapToSpeak: 'बोलने के लिए टैप करें',
    
    // Categories
    crops: 'फसलें',
    cropDescription: 'विभिन्न फसलों, रोपण और देखभाल के बारे में जानें',
    pests: 'कीट',
    pestDescription: 'फसल कीटों की पहचान और प्रभावी प्रबंधन करें',
    soil: 'मिट्टी',
    soilDescription: 'मिट्टी के प्रकार और सुधार के तरीकों को समझें',
    weather: 'मौसम',
    weatherDescription: 'स्थान-आधारित मौसम अपडेट प्राप्त करें',
    schemes: 'सरकारी योजनाएं',
    schemesDescription: 'सरकारी ऋण और कृषि योजनाओं तक पहुंचें',
    market: 'बाजार विश्लेषण',
    marketDescription: 'विभिन्न फसलों की बाजार मांग का विश्लेषण करें',
    pesticides: 'कीटनाशक',
    pesticidesDescription: 'फसल-विशिष्ट कीटनाशक जानकारी खोजें',
    water: 'जल प्रबंधन',
    waterDescription: 'कुशल जल उपयोग और सिंचाई सीखें',
    diseaseDetection: 'रोग पहचान',
    diseaseDescription: 'फसल रोगों की पहचान के लिए चित्र अपलोड करें',
    
    // Chatbot UI
    thinking: 'सोच रहा है...',
    chatbotPlaceholder: 'मुझसे खेती के बारे में पूछें...',
    chatbotGreeting: "नमस्ते! खेती के बारे में कुछ भी पूछें।",
    signInToSaveHistory: "अपना चैट इतिहास सहेजने के लिए साइन इन करें।",
    recording: 'रिकॉर्डिंग...',
    voice: 'आवाज',
    audioOn: 'ऑडियो ऑन',
    audioOff: 'ऑडियो ऑफ',
    youSaid: 'आपने कहा:',
    youAreSaying: "आप कह रहे हैं:",
    listeningSpeakNow: 'सुन रहा है... अब बोलें',
    listening: 'सुन रहा है...',

    // AI Responses
    aiResponseCrop: 'फसलों के बारे में आपके प्रश्न के आधार पर, मैं रोपण, देखभाल और कटाई के बारे में विस्तृत जानकारी के लिए हमारे फसल अनुभाग की जाँच करने की सलाह देता हूँ। विशिष्ट फसल सलाह के लिए, अपनी मिट्टी के प्रकार, जलवायु और स्थानीय स्थितियों जैसे कारकों पर विचार करें। क्या आप चाहते हैं कि मैं किसी विशेष फसल में आपकी मदद करूँ?',
    aiResponsePest: "कीट प्रबंधन के लिए, पहले अपनी फसलों को प्रभावित करने वाले विशिष्ट कीट की पहचान करना महत्वपूर्ण है। मैं जैविक और रासायनिक उपचार दोनों विकल्पों में आपकी मदद कर सकता हूँ। विस्तृत पहचान गाइड और उपचार विधियों के लिए हमारे कीट अनुभाग की जाँच करें। आप किस प्रकार की फसल के साथ काम कर रहे हैं?",
    aiResponseSoil: "सफल खेती के लिए मिट्टी का स्वास्थ्य महत्वपूर्ण है। अलग-अलग मिट्टी के प्रकारों के लिए अलग-अलग प्रबंधन दृष्टिकोण की आवश्यकता होती है। मैं पहले अपनी मिट्टी के पीएच और पोषक तत्वों के स्तर का परीक्षण करने की सलाह देता हूँ। हमारे मिट्टी अनुभाग में मिट्टी के प्रकारों और सुधार के तरीकों के बारे में व्यापक जानकारी है। आपकी वर्तमान मिट्टी की स्थिति क्या है?",
    aiResponseWeather: "खेती के निर्णयों में मौसम महत्वपूर्ण भूमिका निभाता है। मैं वर्तमान मौसम की जानकारी और कृषि संबंधी जानकारी प्रदान कर सकता हूँ। सिंचाई योजना के लिए, वर्तमान परिस्थितियों और पूर्वानुमान दोनों पर विचार करें। विस्तृत कृषि मौसम मार्गदर्शन के लिए हमारे मौसम अनुभाग की जाँच करें।",
    aiResponseMarket: "मांग, मौसम और गुणवत्ता के आधार पर बाजार की कीमतों में उतार-चढ़ाव होता रहता है। मैं वर्तमान बाजार रुझानों का विश्लेषण करने और बिक्री के इष्टतम समय का सुझाव देने में आपकी मदद कर सकता हूँ। हमारा बाजार अनुभाग वास्तविक समय की कीमत की जानकारी और मांग विश्लेषण प्रदान करता है। आप कौन सी फसल बेचने की योजना बना रहे हैं?",
    aiResponseDisease: "पौधों के रोग आपकी फसल को काफी प्रभावित कर सकते हैं। जल्दी पहचान करना ही कुंजी है। आप एआई विश्लेषण के लिए प्रभावित पौधों की तस्वीरें अपलोड करने के लिए हमारी रोग पहचान सुविधा का उपयोग कर सकते हैं। मैं सामान्य रोगों और उनके उपचारों के बारे में भी जानकारी प्रदान कर सकता हूँ। आप क्या लक्षण देख रहे हैं?",
    aiResponseWater: "सतत खेती के लिए कुशल जल प्रबंधन आवश्यक है। मैं आपकी फसल के प्रकार और स्थानीय परिस्थितियों के आधार पर सिंचाई तकनीकों का सुझाव दे सकता हूँ। हमारा जल प्रबंधन अनुभाग विभिन्न सिंचाई विधियों और संरक्षण सुझावों को कवर करता है। आपका वर्तमान सिंचाई सेटअप क्या है?",
    aiResponseScheme: "किसानों के लिए सब्सिडी, ऋण और बीमा कार्यक्रमों सहित विभिन्न सरकारी योजनाएं उपलब्ध हैं। मैं आपको उन योजनाओं को खोजने में मदद कर सकता हूँ जिनके लिए आप पात्र हैं। हमारे योजना अनुभाग में आवेदन प्रक्रियाओं और लाभों के बारे में विस्तृत जानकारी है। आप किस प्रकार की सहायता की तलाश में हैं?",
    aiResponseGreeting: "नमस्ते! मैं आपका एआई कृषि सहायक हूँ। मैं फसलों, कीटों, मिट्टी प्रबंधन, मौसम की जानकारी, बाजार की कीमतों, सरकारी योजनाओं और बहुत कुछ में आपकी मदद कर सकता हूँ। आज मैं आपकी किस कृषि संबंधी प्रश्न में मदद कर सकता हूँ?",
    aiResponseDefault: "आपके प्रश्न के लिए धन्यवाद! मैं आपकी सभी खेती की जरूरतों में मदद करने के लिए यहाँ हूँ। मैं फसलों, कीट प्रबंधन, मिट्टी के स्वास्थ्य, मौसम की स्थिति, बाजार की कीमतों, सरकारी योजनाओं और बहुत कुछ के बारे में जानकारी प्रदान कर सकता हूँ। क्या आप कृपया इस बारे में अधिक विशिष्ट हो सकते हैं कि आप क्या जानना चाहते हैं? आप विस्तृत जानकारी के लिए हमारे विभिन्न अनुभागों का भी पता लगा सकते हैं।",
    aiResponseError: "क्षमा करें, मुझे एक त्रुटि हुई। कृपया पुन: प्रयास करें।",

    // Disease Detection Page
    readyToAnalyze: 'विश्लेषण के लिए तैयार',
    uploadToStartDetection: 'रोग पहचान शुरू करने के लिए अपनी फसल की छवि अपलोड करें',
    analyzingImage: 'छवि का विश्लेषण कर रहा है... इसमें कुछ समय लग सकता है।',
    detectionResults: 'पहचान के परिणाम',
    severity: 'तीव्रता',
    high: 'उच्च',
    medium: 'मध्यम',
    low: 'कम',
    confidence: 'आत्मविश्वास',
    getExpertConsultation: 'विशेषज्ञ परामर्श प्राप्त करें',
    saveResults: 'परिणाम सहेजें',
    commonCropDiseases: 'सामान्य फसल रोग',
    affects: 'प्रभावित करता है',
    risk: 'जोखिम',
    selectImage: 'छवि चुनें',
    orClickToSelect: 'या फ़ाइल चुनने के लिए क्लिक करें',
    tipsForDetection: 'बेहतर पहचान के लिए सुझाव',
    preventionTips: 'निवारण सुझाव',
    tip1: 'प्रभावित पौधों के हिस्सों की स्पष्ट, अच्छी रोशनी वाली तस्वीरें लें',
    tip2: 'उन पत्तियों, तनों या फलों पर ध्यान केंद्रित करें जो लक्षण दिखा रहे हैं',
    tip3: 'धुंधली या दूर की छवियों से बचें',
    tip4: 'यदि संभव हो तो कई कोण शामिल करें',

    // Weather
    currentWeather: 'वर्तमान मौसम',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    windSpeed: 'हवा की गति',
    condition: 'स्थिति',
    
    // General
    exploreCategories: 'श्रेणियों का अन्वेषण करें',
    aiAssistant: 'AI सहायक',
    aiDescription: 'खेती के बारे में प्रश्न पूछें, व्यक्तिगत सलाह प्राप्त करें, और अपनी पसंदीदा भाषा में विशेषज्ञ ज्ञान तक पहुंचें',
    askQuestion: 'प्रश्न पूछें',
    learnMore: 'और जानें',
    
    // Footer
    footerDescription: 'AI-संचालित कृषि सहायता के साथ भारतीय किसानों को सशक्त बनाना',
    features: 'विशेषताएं',
    voiceAssistant: 'वॉयस असिस्टेंट',
    cropGuidance: 'फसल मार्गदर्शन',
    pestManagement: 'कीट प्रबंधन',
    weatherUpdates: 'मौसम अपडेट',
    support: 'सहायता',
    helpCenter: 'सहायता केंद्र',
    tutorials: 'ट्यूटोरियल',
    contact: 'संपर्क',
    feedback: 'फीडबैक',
    languages: 'भाषाएं',
    allRightsReserved: 'सभी अधिकार सुरक्षित।',
    
    // Navigation
    home: 'होम',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    
    // Chat
    chatHistory: 'चैट इतिहास',
    startChatting: 'चैट शुरू करें',
    totalConversations: 'कुल बातचीत',
    todaysChats: 'आज की चैट',
    daysActive: 'सक्रिय दिन',
    
    // Common
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    retry: 'पुनः प्रयास',
    save: 'सेव',
    cancel: 'रद्द',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    search: 'खोजें',
    filter: 'फिल्टर',
    sort: 'क्रमबद्ध करें',
    
    // Additional Hindi translations...
    back: 'वापस',
    noCropsFound: 'कोई फसलें नहीं मिलीं',
    noPestsFound: 'कोई कीट नहीं मिले',
    noSoilTypesFound: 'कोई मिट्टी के प्रकार नहीं मिले',
    noSchemesFound: 'कोई योजनाएं नहीं मिलीं',
    noPesticidesFound: 'कोई कीटनाशक नहीं मिले',
    noTechniquesFound: 'कोई तकनीकें नहीं मिलीं',
    tryDifferentSearch: 'अलग खोज का प्रयास करें',
    cropName: 'फसल का नाम',
    plantingInstructions: 'रोपण निर्देश',
    careGuidelines: 'देखभाल दिशानिर्देश',
    harvestingInfo: 'कटाई की जानकारी',
    expectedYield: 'अपेक्षित उपज',
    suitableRegions: 'उपयुक्त क्षेत्र',
    
    pestName: 'कीट का नाम',
    scientificName: 'वैज्ञानिक नाम',
    identification: 'पहचान',
    damage: 'होने वाला नुकसान',
    organicManagement: 'जैविक प्रबंधन',
    chemicalManagement: 'रासायनिक प्रबंधन',
    affectedCrops: 'प्रभावित फसलें',
    
    soilType: 'मिट्टी का प्रकार',
    properties: 'मुख्य गुण',
    distribution: 'भौगोलिक वितरण',
    suitableCrops: 'उपयुक्त फसलें',
    improvements: 'स्वास्थ्य सुधार सिफारिशें',
    
    schemeName: 'योजना का नाम',
    description: 'विवरण',
    benefits: 'लाभ',
    eligibility: 'पात्रता मानदंड',
    applicationProcess: 'आवेदन प्रक्रिया',
    officialUrl: 'आधिकारिक वेबसाइट',
    launchDate: 'लॉन्च तारीख',
    
    pesticideName: 'कीटनाशक का नाम',
    pesticideType: 'प्रकार',
    activeIngredients: 'सक्रिय तत्व',
    targetCrops: 'लक्षित फसलें',
    applicationInstructions: 'उपयोग निर्देश',
    safetyPrecautions: 'सुरक्षा सावधानियां',
    
    techniqueName: 'तकनीक का नाम',
    irrigationMethod: 'सिंचाई विधि',
    conservationTips: 'संरक्षण सुझाव',
    applicableCrops: 'लागू फसलें',
    
    uploadImage: 'चित्र अपलोड करें',
    detectDisease: 'रोग की पहचान करें',
    symptoms: 'लक्षण',
    causes: 'कारण',
    treatment: 'उपचार विकल्प',
  }
};

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set, get) => ({
      currentLanguage: 'en',
      setLanguage: (language: string) => set({ currentLanguage: language }),
      t: (key: string) => {
        const { currentLanguage } = get();
        const translation = translations[currentLanguage as keyof typeof translations];
        return translation?.[key as keyof typeof translation] || translations.en[key as keyof typeof translations.en] || key;
      },
    }),
    {
      name: 'language-storage',
    }
  )
);